# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reduction < Formula
  desc "Stream processing engine"
  homepage "https://reduction.dev"
  version "0.0.1-test"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1-test/reduction_0.0.1-test_darwin_amd64"
      sha256 "f65b294139cda6dc9d6cbbaeb56fb61ec912d394ef5c49cc51d0b19d0a3fee95"

      def install
        bin.install "reduction_0.0.1-test_darwin_amd64" => "reduction"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1-test/reduction_0.0.1-test_darwin_arm64"
      sha256 "63176e837d967434650b821d5963f97d165ef8db2ee04ea487083adbce21716c"

      def install
        bin.install "reduction_0.0.1-test_darwin_arm64" => "reduction"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1-test/reduction_0.0.1-test_linux_amd64"
        sha256 "55c1487f0b3cd5b2006c3e6be53ee539e19bede3d816ec62727ac244b7078529"

        def install
          bin.install "reduction_0.0.1-test_linux_amd64" => "reduction"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1-test/reduction_0.0.1-test_linux_arm64"
        sha256 "2a8852732f009084bcd848eb51b5555703fd8166c0e217d38d8a9bdd16687713"

        def install
          bin.install "reduction_0.0.1-test_linux_arm64" => "reduction"
        end
      end
    end
  end

  test do
    system "#{bin}/reduction version"
  end
end
