# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reduction < Formula
  desc "Stream processing engine"
  homepage "https://reduction.dev"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1/reduction_0.0.1_darwin_amd64"
      sha256 "0b0c6684e7c850189835cb1faf1e3cddb61ab66a6923bf253e017fb56f423a28"

      def install
        bin.install "reduction_0.0.1_darwin_amd64" => "reduction"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1/reduction_0.0.1_darwin_arm64"
      sha256 "7ce8ad014f4c96ab96a0cf6e94a745334defccfb305f893e11d8a02895998837"

      def install
        bin.install "reduction_0.0.1_darwin_arm64" => "reduction"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1/reduction_0.0.1_linux_amd64"
        sha256 "8057b0d590c2dc8464199eafebd6f326902d26000595547750b1a535bcb06968"

        def install
          bin.install "reduction_0.0.1_linux_amd64" => "reduction"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reduction-dev/reduction/releases/download/v0.0.1/reduction_0.0.1_linux_arm64"
        sha256 "422907c19004bc1b400247e52cf7b6073891429a81081a8bab82e49fa1cf550b"

        def install
          bin.install "reduction_0.0.1_linux_arm64" => "reduction"
        end
      end
    end
  end

  test do
    system "#{bin}/reduction version"
  end
end
